### ISSUE TITLE
csrf non compliant

### ISSUE THREAD

**Issue by yalgva** [99net/Timesheet#1]
Hello

After installation I had csrf not compliant.
I fixed it by modifying setup.php  line 12

$PLUGIN_HOOKS['csrf_compliant']['timesheet'] = true;

by

$PLUGIN_HOOKS['csrf_compliant']['Timesheet'] = true;

Timesheet syntax error with T not t

Thx to fix your pacakge

**Comment by 99net** [comment]
Done.  Thx for support.
