### ISSUE TITLE
Timesheet icon

### ISSUE THREAD

**Issue by 99net** [99net/Timesheet#6]
Timesheet icon missing from dropdown menu. (Assistance > Timesheet)
Icon source: https://plugins.glpi-project.org/#/plugin/Timesheet

![image](https://user-images.githubusercontent.com/43380069/143703108-c5f1998d-cdc7-4312-8a4e-9349f52911e4.png)

**Comment by mindc** [comment]
fixed in https://github.com/99net/Timesheet/commit/c56820cecab6b45d869a2b5c70797cdfa5b274f4
